[release]
auto_version = false
always_commit_message = false
create_tag = true
push = true

[homebrew]
enabled = true

formula="Formula/q-tip-uikit.rb"
repository="."

commit_message = "Update UIKit to {version}"
push = true

[cmake]
enabled = true

update_cmake_project_version = true
cmake_project_name = "QTipUIKit"

cmake_lists_directory = "."
