name: CMake

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]


jobs:

  build:

    runs-on: ${{ matrix.os }}

    strategy:

      fail-fast: false

      matrix:

        include:

          # macOS
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++

          # Linux / GCC
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++

          # Linux / Clang
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++


    steps:

      # ------------------------------------------------------
      # Checkout
      # ------------------------------------------------------

      - name: Checkout
        uses: actions/checkout@v4


      # ------------------------------------------------------
      # Install CMake
      # ------------------------------------------------------

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 4.0.x


      # ------------------------------------------------------
      # Install Q-Tip
      # ------------------------------------------------------

      - name: Install Q-Tip
        run: |
          brew trust propythoncoderaya/q-tip
          brew tap ProPythonCoderAya/q-tip
          brew install q-tip


      # ------------------------------------------------------
      # Configure
      # ------------------------------------------------------

      - name: Configure CMake
        run: >
          cmake
          -B build
          -S .
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_BUILD_TYPE=Release


      # ------------------------------------------------------
      # Build
      # ------------------------------------------------------

      - name: Build
        run: |
          cmake --build build --config Release --parallel


      # ------------------------------------------------------
      # Test
      # ------------------------------------------------------

      - name: Test
        working-directory: build
        run: |
          ctest --build-config Release --output-on-failure
